server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diplom1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tqw1467gheK

  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml
    url: jdbc:mysql://localhost:3306/diplom1
    user: root
    password: tqw1467gheK

  jpa:
    show-sql: true