server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://${DATABASE_URL}/diplom1 #jdbc:mysql://localhost:3306/diplom1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER} #root
    password: ${DATABASE_PASSWORD}  #root


  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml
    url: jdbc:mysql://${DATABASE_URL}/diplom1
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: true

    properties:
      hibernate:
        format_sql: true